# Generated by Django 2.0.6 on 2019-04-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='random_text',
        ),
    ]
