# Generated by Django 2.0.6 on 2019-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_home_random_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='random_text',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
