# Generated by Django 2.0.6 on 2019-04-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_random_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='decrypt_text',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='dif_key',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='encrypt_text',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
